2019-07-21 23:58:57,979 ERROR: Exception on /index [GET] [in /home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/liuliu/Downloads/FlaskApp_after_sju/FlaskApp/__init__.py", line 414, in index
    prev_url=prev_url)
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/liuliu/Downloads/FlaskApp_after_sju/FlaskApp/templates/showimg.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/liuliu/Downloads/FlaskApp_after_sju/FlaskApp/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/liuliu/Downloads/FlaskApp_after_sju/FlaskApp/templates/base.html", line 57, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/liuliu/Downloads/FlaskApp_after_sju/FlaskApp/templates/showimg.html", line 45, in block "app_content"
    <a href="{{ url_for('showascategory', categoryName=category) }}">{{category}}</a>
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'showascategory' with values ['categoryName']. Did you mean 'changecategory' instead?
2019-07-22 00:01:32,654 INFO: cshopperstore [in /home/liuliu/Downloads/FlaskApp_after_sju/FlaskApp/__init__.py:112]
2019-07-22 00:01:36,521 ERROR: Exception on /index [GET] [in /home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/liuliu/Downloads/FlaskApp_after_sju/FlaskApp/__init__.py", line 414, in index
    prev_url=prev_url)
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/liuliu/Downloads/FlaskApp_after_sju/FlaskApp/templates/showimg.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/home/liuliu/Downloads/FlaskApp_after_sju/FlaskApp/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/home/liuliu/Downloads/FlaskApp_after_sju/FlaskApp/templates/base.html", line 57, in block "content"
    {% block app_content %}{% endblock %}
  File "/home/liuliu/Downloads/FlaskApp_after_sju/FlaskApp/templates/showimg.html", line 45, in block "app_content"
    <a href="{{ url_for('showascategory', categoryName=category) }}">{{category}}</a>
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/liuliu/Documents/chaoqun_shopping_web/env/lib/python3.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'showascategory'. Did you forget to specify values ['categoryName']?
2019-07-22 00:02:47,569 INFO: cshopperstore [in /home/liuliu/Downloads/FlaskApp_after_sju/FlaskApp/__init__.py:112]
2019-07-22 00:04:33,683 INFO: cshopperstore [in /home/liuliu/Downloads/FlaskApp_after_sju/FlaskApp/__init__.py:112]
2019-07-22 00:04:51,699 INFO: cshopperstore [in /home/liuliu/Downloads/FlaskApp_after_sju/FlaskApp/__init__.py:112]
2019-07-22 00:05:18,898 INFO: cshopperstore [in /home/liuliu/Downloads/FlaskApp_after_sju/FlaskApp/__init__.py:112]
